### ISSUE TITLE
grab/ti.go:53 panic问题

### ISSUE THREAD

**Issue by xishir** [zema1/watchvuln#21]
panic: runtime error: integer divide by zero

goroutine 72 [running]:
github.com/zema1/watchvuln/grab.(*TiCrawler).GetPageCount(0xc00038ee80, {0x110ae38?, 0xc0002d3f80}, 0x64)
	github.com/zema1/watchvuln/grab/ti.go:53 +0x3be
main.initData({0x110ae38, 0xc0002d3f80}, 0xc0002d3780, {0x110b848, 0xc00038ee80})
	github.com/zema1/watchvuln/main.go:386 +0xd5
main.Action.func1()
	github.com/zema1/watchvuln/main.go:188 +0x2d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

**Comment by imemaker** [comment]
i have the same problem too!!!

**Comment by sairson** [comment]
![image](https://user-images.githubusercontent.com/74412075/230696090-71a95bdf-d3a3-49b8-b287-926743d82372.png)
同样的问题

**Comment by imemaker** [comment]
@zema1

**Comment by astring0** [comment]
奇安信ti的接口一个ip速度请求过快的话，服务端会返回一个空表

**Comment by Ghr07h** [comment]
而53行没有考虑过pageCount为空的情况，可以把pageCount提前判断一下不为零即可向下运行，不过还是要达到预期效果还是要控制一下访问间隔的
```
# Line 53
if pageCount != 0 && total%pageCount != 0
```
