### ISSUE TITLE
v0.6.0版本的qax数据源存在bug

### ISSUE THREAD

**Issue by M09Ic** [zema1/watchvuln#24]
logs:

```
[WARN] 2023/04/12 00:06 [qianxin-ti]: invalid total size 0
[WARN] 2023/04/12 00:06 retrying as %!s(<nil>)
[WARN] 2023/04/12 00:06 [qianxin-ti]: invalid total size 0
[WARN] 2023/04/12 00:06 retrying as %!s(<nil>)
[INFO] 2023/04/12 00:06 [qianxin-ti]: parsing page 1
```

v0.4.0能正常获取, 但是会报错退出, 更新到v0.6.0后似乎qax的数据源获取失败

![image](https://user-images.githubusercontent.com/29176200/231223685-24e394a0-8f31-4a3a-967c-00ca1e7c4523.png)

**Comment by zema1** [comment]
奇安信这个接口如果访问频率太快容易被 ban，这个 ban 的策略和 ip 有关，我在服务器上发现还是能正常抓取的，偶尔也会报错。
0.6.0 做了一些 retry，但如果 retry 3次还是失败了，就不再继续抓取了。

打算改进一下抓取策略，其实不必全部抓取，只需抓取前10页做个基础数据就可以，后面发版改下

**Comment by M09Ic** [comment]
感觉可以不用每个人重复抓取， 可以把sqlite数据库打包到代码中， 随着每个版本发布.  这样只需要监控第一页数据。

**Comment by zema1** [comment]
想了一下，内置的确实是一种不错改进方案。不过这种方案要求我能定期发版才行，比如一个月发一次版，那么内置的db数据可能就比较老了，还是要重新抓取。所以其实抓取个前三页应该是最快的，也好实现

**Comment by zema1** [comment]
已修复，更新后如果还有问题可以新开 issue https://github.com/zema1/watchvuln/releases/tag/v0.7.0
