### ISSUE TITLE
报错了 不推送数据了

### ISSUE THREAD

**Issue by Cha0sJ** [zema1/watchvuln#25]
[INFO] 2023/04/11 13:15 [oscs]: parsing page 1
[INFO] 2023/04/11 13:15 [oscs]: page 1 contains 10 vulns
[INFO] 2023/04/11 13:15 [aliyun-avd]: parsing page https://avd.aliyun.com/high-risk/list?page=1
panic: runtime error: integer divide by zero

goroutine 1220 [running]:
github.com/zema1/watchvuln/grab.(*TiCrawler).GetPageCount(0xc0002d5060, {0x10f9358?, 0xc00007ed40}, 0xa)
        github.com/zema1/watchvuln/grab/ti.go:53 +0x3be
main.collectUpdate.func1()
        github.com/zema1/watchvuln/main.go:302 +0xa4
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
已经不推送数据了，重新运行软件也不行

**Comment by flyinbedxyz** [comment]
一直初始化，阿里漏洞库前端改了？

**Comment by zema1** [comment]
报错的是老版本，新版 v0.6.0 不会报错崩溃。可以更新一下版本看一下有无问题，如果还有问题，请前往该 issue 追溯后续

related to https://github.com/zema1/watchvuln/issues/24

**Comment by 10cks** [comment]
更新最新版，已修复

**Comment by zema1** [comment]
已修复，更新后如果还有问题可以新开 issue https://github.com/zema1/watchvuln/releases/tag/v0.7.0
