### ISSUE TITLE
get 阿里云数据源失败

### ISSUE THREAD

**Issue by YUYANG1229** [zema1/watchvuln#26]
get 阿里云数据源失败 部分漏洞情报数据无法获
![fc11e1eef2ef22b357d26e1bcf8bf83](https://user-images.githubusercontent.com/50980026/231427098-39549c2d-58a0-4808-a131-7969ef2add0c.png)

**Comment by zema1** [comment]
已修复，更新后如果还有问题可以新开 issue https://github.com/zema1/watchvuln/releases/tag/v0.7.0

**Comment by TerickJojo** [comment]
大哥大哥，最新版的阿里数据源又报错了
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/24235319/233295864-7f352701-bc1b-464e-b7b0-9877c1d1f66b.png">

**Comment by zema1** [comment]
这个ip可能触发

**Comment by zema1** [comment]
不是代码的问题，close 了
