### ISSUE TITLE
建议增加钉钉机器人的测试数据

### ISSUE THREAD

**Issue by 333123www** [zema1/watchvuln#3]
建议增加钉钉机器人的测试数据demo。我完成了系统的docker搭建，无法通过日志来准确判断是否搭建成功。当前漏洞库接口中没有最新的漏洞信息，我的机器人没有给我发送相关消息。我只能保证机器人的token和secret正确。

**Comment by zema1** [comment]
https://github.com/zema1/watchvuln/pull/4
