### ISSUE TITLE
奇安信威胁情报

### ISSUE THREAD

**Issue by wtq-tt** [zema1/watchvuln#40]
奇安信威胁情报https://ti.qianxin.com/vulnerability  是不是应该爬https://ti.qianxin.com/vulnerability/list

**Comment by zema1** [comment]
那个漏洞太多了，很多没用的洞。奇安信这个地址确实该换了，之前 ti 那边有个关键漏洞的页面移到 nox 里了，
现在应该用 https://nox.qianxin.com/KeyPoint

不过接口还能用，空了改下

**Comment by passwa11** [comment]
[qianxin-nox]: failed to get page count, msg: 访问次数达到上限!, retrying

**Comment by passwa11** [comment]
> [qianxin-nox]: failed to get page count, msg: 访问次数达到上限!, retrying

建议修改初始化逻辑，其中任何源失败还是继续走剩下的其余源逻辑
