### ISSUE TITLE
师傅考虑集成微步在线的漏洞公告吗？

### ISSUE THREAD

**Issue by ZFYy1x** [zema1/watchvuln#48]

**Comment by zema1** [comment]
感觉它微信公众号可以考虑集成，但微信公众号的爬取有点费劲..

**Comment by jweny** [comment]
> 感觉它微信公众号可以考虑集成，但微信公众号的爬取有点费劲..

那咋整

**Comment by zema1** [comment]
爬不了，主要是你们公众号结构还不统一，没法写爬虫规则。放弃了，等你给我接口

**Comment by hi-unc1e** [comment]
我来试试：
- 微步在线研究响应中心
- http://wechat.doonsec.com/wechat_echarts/?biz=MzI5NjA0NjI5MQ==

**Comment by hi-unc1e** [comment]
> 公众号结构还不统一

确实，需要用xpath之类的办法解析出漏洞优先级，否则用正则匹配效果很差

**Comment by zema1** [comment]
公众号文章的获取可以用这个 https://wechat2rss.xlab.app/feed/ac64c385ebcdb17fee8df733eb620a22b979928c.xml

我差点就加上了，但是公众号文章格式太不统一了，xpath 都没法写统一的规则去解析，所以放弃了。欢迎你继续尝试。
