### ISSUE TITLE
师傅知道创宇没有爬了嘛 

### ISSUE THREAD

**Issue by notalkingya** [zema1/watchvuln#49]
师傅知道创宇没有爬了嘛

**Comment by zema1** [comment]
seebug 这个代码逻辑是有些的，但默认禁用了，原因如下：
1. 网站有 waf 防护，虽然写了 bypass 逻辑，但偶尔还是会失效，失效会报错
2. seebug 的数据源质量一般，更新不算及时

如果想手动启用，需要指定一下启动参数：

- 命令行启动加个  `-s avd,nox,oscs,seebug`
- docker启动加个 `-e SOURCES=avd,nox,oscs,seebug`

**Comment by notalkingya** [comment]
> seebug 这个代码逻辑是有些的，但默认禁用了，原因如下：
> 
> 1. 网站有 waf 防护，虽然写了 bypass 逻辑，但偶尔还是会失效，失效会报错
> 2. seebug 的数据源质量一般，更新不算及时
> 
> 如果想手动启用，需要指定一下启动参数：
> 
> * 命令行启动加个  `-s avd,nox,oscs,seebug`
> * docker启动加个 `-e SOURCES=avd,nox,oscs,seebug`

  好的 谢谢师傅
