### ISSUE TITLE
飞书推送疑似失效？

### ISSUE THREAD

**Issue by flyinbedxyz** [zema1/watchvuln#55]
watchvuln-windows-amd64.exe --lark-access-token aaaa
[FTAL] 2023/11/14 13:36 [main]:
you must setup a pusher, eg:
use dingding: watchvuln-windows-amd64.exe --dt DINGDING_ACCESS_TOKEN --ds DINGDING_SECRET
use wechat:   watchvuln-windows-amd64.exe --wk WECHATWORK_KEY
use API:   watchvuln-windows-amd64.exe --webhook WEBHOOK_URL

**Comment by flyinbedxyz** [comment]
补充一下，好像必须加签跑，但是加签名跑的话会失败，code：19021
msg：sign match fail or timestamp is not within one hour from current time

**Comment by flyinbedxyz** [comment]
目前可以通过不设置需要加签，然后可以加一个假的签名参数去飞书

**Comment by zema1** [comment]
试了一下可以正常推送的，现在的实现必须启用加签并配置上正确的签名
