### ISSUE TITLE
漏洞过滤

### ISSUE THREAD

**Issue by MochizukiSec** [zema1/watchvuln#56]
可不可以过滤漏洞信息？如只有OA系统，那么我只需要接受OA的漏洞预警。

**Comment by zema1** [comment]
这个需求不太通用，适合自己写个 webhook server 来过滤下，可以在那里面再调用 watchvuln 的推送逻辑。或者直接改改 watchuln 改成适合自己的过滤，比如在这之前加几个 if 

https://github.com/zema1/watchvuln/blob/main/ctrl/ctrl.go#L223

**Comment by MochizukiSec** [comment]
谢谢指点 我明白了。
