### ISSUE TITLE
最新版本企业微信不推送漏洞情报

### ISSUE THREAD

**Issue by ThestaRY7** [zema1/watchvuln#58]
情况：
启动后能正常弹出以下信息：
数据初始化完成，当前版本 v1.3.0， 本地漏洞数量: 137, 检查周期: 30m0s 
启用的数据源:
 
- 阿里云漏洞库
- 奇安信威胁情报中心
- OSCS开源安全情报预警
- 微步在线研究响应中心-漏洞通告

结束后也弹出了：
注意: WatchVuln 进程退出

但是没有推送任何漏洞情报，使用--dubug参数查看，也未提示异常告警，是否可以增加一个--dubug-check 类似参数，发送一条测试数据，看看哪里出了问题？谢谢

**Comment by zema1** [comment]
有了这个提示说明是正常的，没有推送因为现在没有新漏洞呀

**Comment by ThestaRY7** [comment]
这样吗，但是从昨天到今天都没有新漏洞推送正常吗，因为别的机器人有推送，比如：I Doc View 任意文件上传漏洞

**Comment by zema1** [comment]
不正常的，你确定服务有在正常运行么，不要让进程或服务退出。然后你需要更新到最新版本，最新版是 v1.4.2

**Comment by ThestaRY7** [comment]
换了个服务器就解决了，不懂为什么。。。
