### ISSUE TITLE
demand suggestion

### ISSUE THREAD

**Issue by epony4c** [zema1/watchvuln#6]
1. 希望能过通过加载配置文件设定接受推送全部或者部分漏洞提醒。
2. 要是能加个公众号推送就更好了！

lz NB！

**Comment by zema1** [comment]
Done In https://github.com/zema1/watchvuln/pull/12

增加了一个选项 `no-filter` 和环境变量 `NO_FILTER` ，启用的时候将推送所有爬到的漏洞而不过滤，一会我更新下文档发个版。

公众号推送暂时没有规划，和这个项目主要逻辑也不太相关，这个问题先 close 了
