### ISSUE TITLE
师傅能否加一个重点关注列表

### ISSUE THREAD

**Issue by f1ashine** [zema1/watchvuln#84]
对于企业来说，使用的那些系统只有一部分是通用的，平时只需要关注一些在使用的系统是否有漏洞信息披露就够了，所以能否加一个配置列表用于匹配相关产品的名字，这样推送的时候可以过滤一些无用的信息，或者说匹配到之后在推送的时候加上一些关键字，如“【重点关注】”，这样看到推送的时候就会比较注意了。

**Comment by zema1** [comment]
需求合理，我这周做一下
