### ISSUE TITLE
建议增加通过配置文件来加载配置

### ISSUE THREAD

**Issue by Fiary-Tale** [zema1/watchvuln#86]
可以通过读取yaml或json或toml等配置文件来加载配置，并可以通过参数来更新配置文件加载

**Comment by zema1** [comment]
这个不打算做了，因为虽然参数比较多，实际使用起来只会用到3个左右的参数，直接命令行或环境变量要简单很多。
实际上，如果你想用配置文件的方式，不如试试 docker-compose 的方式启动，在yaml定义里写环境变量，也能实现你的需求。

**Comment by Fiary-Tale** [comment]
没关系，感谢作者的开源，我可以自行添加读取配置文件的操作来实现，只是我不喜欢在进程中存在任何关于token或其他的东西，曾经有幸见过黑产大佬，在进程中存放了token
