### ISSUE TITLE
只想导入数据库不推送

### ISSUE THREAD

**Issue by moondeft** [zema1/watchvuln#90]
大佬，只想把信息保存在数据，禁用掉推送应该怎么做

**Comment by zema1** [comment]
这里限制了必须有至少一个推送方式，把这行注释掉应该就行。

https://github.com/zema1/watchvuln/blob/6d8ef9409db9052c796859841b0753363d038f56/main.go#L439

**Comment by moondeft** [comment]
可以了，感谢大佬
