### ISSUE TITLE
這三個數據原獲取失敗

### ISSUE THREAD

**Issue by qoo7972365** [zema1/watchvuln#92]
![image](https://github.com/user-attachments/assets/686f5f38-20f9-46ce-8b91-514030ecb214)

**Comment by zema1** [comment]
这大概率是网络问题引起的，请尝试使用云服务器之类的重试一下。
如果还不行，可以考虑给 watchvuln 配置一个代理 https://github.com/zema1/watchvuln?tab=readme-ov-file#%E9%85%8D%E7%BD%AE%E4%BB%A3%E7%90%86
