### ISSUE TITLE
 init data: seebug: get page count: failed to get pagination node

### ISSUE THREAD

**Issue by HuiTaiL6** [zema1/watchvuln#94]
[root@~]# screen -r watchvuln
./watchvuln-linux-amd64  --dt xxx--ds xxx-i 1m

。。。。。。
  
[ERRO] 2024/08/12 09:15 [ctrl]: init data: seebug: get page count: failed to get pagination node
[INFO] 2024/08/12 09:15 [ctrl]: system init finished, local database has 824 vulns
[INFO] 2024/08/12 09:15 [pusher-dingding]: sending markdown WatchVuln 初始化完成

**Comment by zema1** [comment]
seebug 更新了页面逻辑，我这两天更新一下爬虫逻辑

**Comment by zema1** [comment]
可以先把这个源禁用掉来使用
