### ISSUE TITLE
docker   server酱已经废弃接口sc.ftqq.com，应改用 sctapi.ftqq.com 作为调用入口

### ISSUE THREAD

**Issue by JokeJ666** [zema1/watchvuln#95]
docker   server酱已经废弃接口sc.ftqq.com，应改用 sctapi.ftqq.com 作为调用入口

**Comment by JokeJ666** [comment]
![image](https://github.com/user-attachments/assets/7e858a71-aba9-475f-abd5-b698b8900600)

**Comment by zema1** [comment]
方便来个 pr 不
